"""Add numVotes to movies table

Revision ID: 046c6c660987
Revises: 2031bd1913e4
Create Date: 2025-07-30 16:43:08.173494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046c6c660987'
down_revision: Union[str, Sequence[str], None] = '2031bd1913e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('numVotes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'numVotes')
    # ### end Alembic commands ###
