"""Add favorite_genres to users table

Revision ID: 2031bd1913e4
Revises: 06778fd25944
Create Date: 2025-07-28 15:51:31.290415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2031bd1913e4'
down_revision: Union[str, Sequence[str], None] = '06778fd25944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_genres')
    # ### end Alembic commands ###
